[project]
name = "algos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.1",
    "pathlib2>=2.3.7.post1",
    "pyqt5==5.15.10",
    "pytest>=8.3.5",
]
